var classes = [
    {
        "name": "App\\Controller\\Dashboard\\CategoryDashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "categories",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deletePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\CategoryRepository",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Category",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Category",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\CategoryRepository",
            "App\\Entity\\Category"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 118,
        "vocabulary": 35,
        "volume": 605.26,
        "difficulty": 8,
        "effort": 4842.04,
        "level": 0.13,
        "bugs": 0.2,
        "time": 269,
        "intelligentContent": 75.66,
        "number_operators": 22,
        "number_operands": 96,
        "number_operators_unique": 5,
        "number_operands_unique": 30,
        "cloc": 12,
        "loc": 62,
        "lloc": 50,
        "mi": 74.02,
        "mIwoC": 42.52,
        "commentWeight": 31.5,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 196.67,
        "totalStructuralComplexity": 784,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 786.67,
        "package": "App\\Controller\\Dashboard\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\Dashboard\\CommentDashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "comments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deletePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\CommentRepository",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\CommentRepository",
            "App\\Entity\\Comment"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 38,
        "vocabulary": 20,
        "volume": 164.23,
        "difficulty": 4,
        "effort": 656.93,
        "level": 0.25,
        "bugs": 0.05,
        "time": 36,
        "intelligentContent": 41.06,
        "number_operators": 6,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 4,
        "loc": 23,
        "lloc": 19,
        "mi": 86.43,
        "mIwoC": 56.32,
        "commentWeight": 30.1,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.64,
        "relativeSystemComplexity": 36.64,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.29,
        "totalSystemComplexity": 73.29,
        "package": "App\\Controller\\Dashboard\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\Dashboard\\PostDashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "posts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addPost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editPost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deletePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\PostRepository",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Post",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Post",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\PostRepository",
            "App\\Entity\\Post"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 120,
        "vocabulary": 35,
        "volume": 615.51,
        "difficulty": 8.17,
        "effort": 5026.7,
        "level": 0.12,
        "bugs": 0.21,
        "time": 279,
        "intelligentContent": 75.37,
        "number_operators": 22,
        "number_operands": 98,
        "number_operators_unique": 5,
        "number_operands_unique": 30,
        "cloc": 20,
        "loc": 70,
        "lloc": 50,
        "mi": 79.3,
        "mIwoC": 42.47,
        "commentWeight": 36.83,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 169.71,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 2.86,
        "totalSystemComplexity": 678.86,
        "package": "App\\Controller\\Dashboard\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\Dashboard\\UserDashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "users",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deletePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\UserRepository",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "App\\Service\\Mailjet\\Mailing\\UserMailing",
            "Doctrine\\Persistence\\ManagerRegistry",
            "Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Doctrine\\Persistence\\ManagerRegistry",
            "Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface",
            "App\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\UserRepository",
            "App\\Entity\\User"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 128,
        "vocabulary": 40,
        "volume": 681.21,
        "difficulty": 9.44,
        "effort": 6431.39,
        "level": 0.11,
        "bugs": 0.23,
        "time": 357,
        "intelligentContent": 72.15,
        "number_operators": 21,
        "number_operands": 107,
        "number_operators_unique": 6,
        "number_operands_unique": 34,
        "cloc": 22,
        "loc": 75,
        "lloc": 53,
        "mi": 78.81,
        "mIwoC": 41.61,
        "commentWeight": 37.2,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 289.54,
        "totalStructuralComplexity": 1156,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 1158.17,
        "package": "App\\Controller\\Dashboard\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "home",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "App\\Repository\\UserRepository",
            "App\\Repository\\CommentRepository",
            "App\\Repository\\PostRepository",
            "App\\Repository\\CategoryRepository"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 20,
        "volume": 159.91,
        "difficulty": 1.72,
        "effort": 275.4,
        "level": 0.58,
        "bugs": 0.05,
        "time": 15,
        "intelligentContent": 92.85,
        "number_operators": 6,
        "number_operands": 31,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 4,
        "loc": 17,
        "lloc": 13,
        "mi": 94.27,
        "mIwoC": 60.13,
        "commentWeight": 34.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 10.25,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\Security\\Http\\Authentication\\AuthenticationUtils",
            "LogicException"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 19,
        "vocabulary": 13,
        "volume": 70.31,
        "difficulty": 1.45,
        "effort": 102.27,
        "level": 0.69,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 48.34,
        "number_operators": 3,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 7,
        "loc": 21,
        "lloc": 14,
        "mi": 100.92,
        "mIwoC": 61.93,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "package": "App\\Controller\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Category",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setName",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSlug",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getParent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setParent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCategories",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPosts",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addPost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 6,
        "nbMethodsSetters": 2,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\Collection",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Post",
            "App\\Entity\\Post"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 79,
        "vocabulary": 14,
        "volume": 300.78,
        "difficulty": 11,
        "effort": 3308.59,
        "level": 0.09,
        "bugs": 0.1,
        "time": 184,
        "intelligentContent": 27.34,
        "number_operators": 24,
        "number_operands": 55,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 28,
        "loc": 111,
        "lloc": 83,
        "mi": 74.94,
        "mIwoC": 39.84,
        "commentWeight": 35.1,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.56,
        "relativeSystemComplexity": 50.56,
        "totalStructuralComplexity": 637,
        "totalDataComplexity": 20.25,
        "totalSystemComplexity": 657.25,
        "package": "App\\Entity\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Comment",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPost",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPost",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUser",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLikes",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addLike",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeLike",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 3,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\User",
            "App\\Entity\\User"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 54,
        "vocabulary": 11,
        "volume": 186.81,
        "difficulty": 10.29,
        "effort": 1921.47,
        "level": 0.1,
        "bugs": 0.06,
        "time": 107,
        "intelligentContent": 18.16,
        "number_operators": 18,
        "number_operands": 36,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 14,
        "loc": 79,
        "lloc": 65,
        "mi": 74.36,
        "mIwoC": 44.01,
        "commentWeight": 30.35,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.74,
        "relativeSystemComplexity": 26.74,
        "totalStructuralComplexity": 275,
        "totalDataComplexity": 19.17,
        "totalSystemComplexity": 294.17,
        "package": "App\\Entity\\",
        "pageRank": 0.23,
        "afferentCoupling": 4,
        "efferentCoupling": 3,
        "instability": 0.43,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Post",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTitle",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSlug",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setSlug",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setContent",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setImage",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCreatedAt",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCreatedAt",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isActive",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setActive",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCategory",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCategory",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setImageFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImageFile",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAuthor",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setAuthor",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getComments",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addComment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeComment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 23,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 11,
        "nbMethodsSetters": 8,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "DateTimeImmutable",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "DateTimeImmutable",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Comment",
            "App\\Entity\\Comment"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 114,
        "vocabulary": 21,
        "volume": 500.72,
        "difficulty": 9.06,
        "effort": 4535.97,
        "level": 0.11,
        "bugs": 0.17,
        "time": 252,
        "intelligentContent": 55.27,
        "number_operators": 37,
        "number_operands": 77,
        "number_operators_unique": 4,
        "number_operands_unique": 17,
        "cloc": 25,
        "loc": 151,
        "lloc": 126,
        "mi": 64.21,
        "mIwoC": 34.74,
        "commentWeight": 29.47,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 3.58,
        "relativeSystemComplexity": 28.58,
        "totalStructuralComplexity": 575,
        "totalDataComplexity": 82.33,
        "totalSystemComplexity": 657.33,
        "package": "App\\Entity\\",
        "pageRank": 0.16,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEmail",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setEmail",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserIdentifier",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRoles",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFirstname",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFirstname",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastname",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setLastname",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPosts",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addPost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removePost",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFullname",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getComments",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addComment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeComment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCommentLike",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCommentLike",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 23,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 9,
        "nbMethodsSetters": 6,
        "wmc": 14,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Post",
            "App\\Entity\\Post",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Comment",
            "App\\Entity\\Comment"
        ],
        "parents": [],
        "implements": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface"
        ],
        "lcom": 2,
        "length": 139,
        "vocabulary": 33,
        "volume": 701.17,
        "difficulty": 8.66,
        "effort": 6072.64,
        "level": 0.12,
        "bugs": 0.23,
        "time": 337,
        "intelligentContent": 80.96,
        "number_operators": 42,
        "number_operands": 97,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 52,
        "loc": 187,
        "lloc": 135,
        "mi": 69.11,
        "mIwoC": 32.66,
        "commentWeight": 36.45,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 2.68,
        "relativeSystemComplexity": 51.68,
        "totalStructuralComplexity": 1127,
        "totalDataComplexity": 61.63,
        "totalSystemComplexity": 1188.63,
        "package": "App\\Entity\\",
        "pageRank": 0.27,
        "afferentCoupling": 5,
        "efferentCoupling": 6,
        "instability": 0.55,
        "violations": {}
    },
    {
        "name": "App\\Form\\CategoryType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "implements": [],
        "lcom": 2,
        "length": 24,
        "vocabulary": 17,
        "volume": 98.1,
        "difficulty": 0,
        "effort": 0,
        "level": 1.42,
        "bugs": 0.03,
        "time": 0,
        "intelligentContent": 138.97,
        "number_operators": 0,
        "number_operands": 24,
        "number_operators_unique": 0,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 62.38,
        "mIwoC": 62.38,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\PostType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "implements": [],
        "lcom": 2,
        "length": 36,
        "vocabulary": 26,
        "volume": 169.22,
        "difficulty": 0,
        "effort": 0,
        "level": 1.44,
        "bugs": 0.06,
        "time": 0,
        "intelligentContent": 244.42,
        "number_operators": 0,
        "number_operands": 36,
        "number_operators_unique": 0,
        "number_operands_unique": 26,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 60.72,
        "mIwoC": 60.72,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Form\\UserType",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "buildForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureOptions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\Form\\AbstractType",
            "Symfony\\Component\\Form\\FormBuilderInterface",
            "Symfony\\Component\\OptionsResolver\\OptionsResolver"
        ],
        "parents": [
            "Symfony\\Component\\Form\\AbstractType"
        ],
        "implements": [],
        "lcom": 2,
        "length": 39,
        "vocabulary": 29,
        "volume": 189.46,
        "difficulty": 0,
        "effort": 0,
        "level": 1.49,
        "bugs": 0.06,
        "time": 0,
        "intelligentContent": 281.76,
        "number_operators": 0,
        "number_operands": 39,
        "number_operators_unique": 0,
        "number_operands_unique": 29,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 60.38,
        "mIwoC": 60.38,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "package": "App\\Form\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\CategoryRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Category",
            "App\\Entity\\Category"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [],
        "lcom": 3,
        "length": 24,
        "vocabulary": 11,
        "volume": 83.03,
        "difficulty": 3.56,
        "effort": 295.78,
        "level": 0.28,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 23.31,
        "number_operators": 5,
        "number_operands": 19,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 36,
        "loc": 65,
        "lloc": 30,
        "mi": 99.5,
        "mIwoC": 53.8,
        "commentWeight": 45.7,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 81.33,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 1.3,
        "totalSystemComplexity": 325.3,
        "package": "App\\Repository\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Repository\\CommentRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Comment",
            "App\\Entity\\Comment"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [],
        "lcom": 3,
        "length": 24,
        "vocabulary": 11,
        "volume": 83.03,
        "difficulty": 3.56,
        "effort": 295.78,
        "level": 0.28,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 23.31,
        "number_operators": 5,
        "number_operands": 19,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 36,
        "loc": 65,
        "lloc": 30,
        "mi": 99.5,
        "mIwoC": 53.8,
        "commentWeight": 45.7,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 81.33,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 1.3,
        "totalSystemComplexity": 325.3,
        "package": "App\\Repository\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Repository\\PostRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\Post",
            "App\\Entity\\Post"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [],
        "lcom": 3,
        "length": 24,
        "vocabulary": 11,
        "volume": 83.03,
        "difficulty": 3.56,
        "effort": 295.78,
        "level": 0.28,
        "bugs": 0.03,
        "time": 16,
        "intelligentContent": 23.31,
        "number_operators": 5,
        "number_operands": 19,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 36,
        "loc": 65,
        "lloc": 30,
        "mi": 99.5,
        "mIwoC": 53.8,
        "commentWeight": 45.7,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 81.33,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 1.3,
        "totalSystemComplexity": 325.3,
        "package": "App\\Repository\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Repository\\UserRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "upgradePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository",
            "Symfony\\Component\\Security\\Core\\User\\PasswordUpgraderInterface",
            "Doctrine\\Persistence\\ManagerRegistry",
            "App\\Entity\\User",
            "App\\Entity\\User",
            "Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface",
            "Symfony\\Component\\Security\\Core\\Exception\\UnsupportedUserException"
        ],
        "parents": [
            "Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository"
        ],
        "implements": [
            "Symfony\\Component\\Security\\Core\\User\\PasswordUpgraderInterface"
        ],
        "lcom": 3,
        "length": 34,
        "vocabulary": 14,
        "volume": 129.45,
        "difficulty": 3.82,
        "effort": 494.26,
        "level": 0.26,
        "bugs": 0.04,
        "time": 27,
        "intelligentContent": 33.9,
        "number_operators": 6,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 39,
        "loc": 76,
        "lloc": 38,
        "mi": 94.86,
        "mIwoC": 50.08,
        "commentWeight": 44.78,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 121.28,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 1.42,
        "totalSystemComplexity": 606.42,
        "package": "App\\Repository\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 6,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Security\\AppDashboardAuthenticator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "authenticate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onAuthenticationSuccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLoginUrl",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Security\\Http\\Authenticator\\AbstractLoginFormAuthenticator",
            "Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface",
            "Symfony\\Component\\Security\\Http\\Authenticator\\Passport\\Passport",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Http\\Authenticator\\Passport\\Badge\\UserBadge",
            "Symfony\\Component\\Security\\Http\\Authenticator\\Passport\\Credentials\\PasswordCredentials",
            "Symfony\\Component\\Security\\Http\\Authenticator\\Passport\\Badge\\CsrfTokenBadge",
            "Symfony\\Component\\Security\\Http\\Authenticator\\Passport\\Passport",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "Symfony\\Component\\Security\\Http\\Authenticator\\AbstractLoginFormAuthenticator"
        ],
        "implements": [],
        "lcom": 3,
        "length": 35,
        "vocabulary": 16,
        "volume": 140,
        "difficulty": 3.23,
        "effort": 452.31,
        "level": 0.31,
        "bugs": 0.05,
        "time": 25,
        "intelligentContent": 43.33,
        "number_operators": 7,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 0,
        "loc": 26,
        "lloc": 26,
        "mi": 53.84,
        "mIwoC": 53.84,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.92,
        "relativeSystemComplexity": 25.92,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 3.67,
        "totalSystemComplexity": 103.67,
        "package": "App\\Security\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Service\\Mailjet\\AbstractMailjet",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateBody",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "templateRender",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Twig\\Environment",
            "App\\Entity\\User",
            "Mailjet\\Client"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 58,
        "vocabulary": 30,
        "volume": 284.6,
        "difficulty": 1.82,
        "effort": 518.38,
        "level": 0.55,
        "bugs": 0.09,
        "time": 29,
        "intelligentContent": 156.25,
        "number_operators": 7,
        "number_operands": 51,
        "number_operators_unique": 2,
        "number_operands_unique": 28,
        "cloc": 17,
        "loc": 47,
        "lloc": 30,
        "mi": 90.59,
        "mIwoC": 50.46,
        "commentWeight": 40.13,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 16.9,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 3.6,
        "totalSystemComplexity": 67.6,
        "package": "App\\Service\\Mailjet\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Service\\Mailjet\\Mailing\\UserMailing",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sendRegistrationMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Service\\Mailjet\\AbstractMailjet",
            "App\\Entity\\User"
        ],
        "parents": [
            "App\\Service\\Mailjet\\AbstractMailjet"
        ],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 7,
        "volume": 42.11,
        "difficulty": 1.17,
        "effort": 49.13,
        "level": 0.86,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 36.09,
        "number_operators": 1,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 113.29,
        "mIwoC": 67.68,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Service\\Mailjet\\Mailing\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    }
]